openapi: 3.0.3
info:
  title: Interoperability APIs - JWKs
  x-logo:
    url: 'https://standards.spdci.org/api-documentation/draft/dci-logo.png'
    backgroundColor: '#FFFFFF'
    altText: 'Digital Convergence Initiative'
  description: Provide JSON Web Key Set to registered clients/services.
  version: 1.0.0
  contact:
    name: DCI Social Protection
    email: info@spdci.org
  license:
   name: DCI Social Protection License
   url: https://github.com/spdci/standards/blob/draft/LICENSE.md
servers:
  - url: "https://sandbox.spdci.org/namespace/v1.0.0"
    description: Sandbox Server
paths:
 /.well-known/jwks.json:
  get: 
    summary: "JWKs : /.well-known/jwks.json"
    description: "This end point is in compliance with RFC 7517 to share the encryption & signature verification public keys over HTTPS channel"
    operationId: get_jwks_json
    responses:
      '200': 
        description: "JSON Web Key Set Response"
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/JWKSResponse"
      '404':
        $ref: "#/components/responses/HttpErrorResponse"
      '500':
        $ref: "#/components/responses/HttpErrorResponse"
    deprecated: false
components:
  schemas:
    JWKSResponse:
      $ref: schema/core/JWKSResponse.yaml
  responses:
    HttpErrorResponse:
      $ref: "../common/response/HttpErrorResponse.yaml"
  
